apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "satisfactory.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- . | toYaml | nindent 8 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "satisfactory.labels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: game-tcp
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: game-udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
            {{- if .Values.service.extraPorts }}
            {{- range .Values.service.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env: {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "satisfactory.fullname" . }}-config
              mountPath: /config
            - name: {{ include "satisfactory.fullname" . }}-server-cache
              mountPath: /config/gamefiles
      volumes:
        {{- range $value := .Values.persistence }}
        - name: {{ include "satisfactory.fullname" $ }}-{{ $value.name }}
          {{- if $value.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "satisfactory.fullname" $ }}-{{ $value.name }}
          {{- else }}
          emptyDir:
            sizeLimit: {{ $value.size}}
          {{ end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
