apiVersion: v1
kind: Service
metadata:
  name: {{ include "satisfactory.fullname" . }}
  labels:
    {{- include "satisfactory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  externalIPs:
  {{- range $externalIP := .Values.service.externalIPs }}
    - {{ $externalIP }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game-tcp
      protocol: TCP
      name: game-tcp
    - port: {{ .Values.service.port }}
      targetPort: game-udp
      protocol: UDP
      name: game-udp
    {{- if .Values.service.extraPorts }}
    {{- range .Values.service.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "satisfactory.selectorLabels" . | nindent 4 }}
